medium_scraper:
  target: dev
  outputs:
   dev:
     type: duckdb
     extensions:
      - json
     path: ':memory:'
     threads: 8
   prod:
     type: duckdb
     extensions:
      - json
     path: ':memory:'
     threads: 8
