repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: medium_scraper
  description: A slightly sarcastic, highly over-engineered GitHub-as-a-Data-Platform Proof-of-Concept.
  homepage: https://pgoslatara.github.io/medium_scraper/
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        checks:
          # https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection
          context: [
            "ci_pipeline / ci_pipeline (3.11)",
          ]
      dismiss_stale_reviews: true
      enforce_admins: true
