name: ci_pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      medium_blog_lookback_days:
        description: The number of days (up to but mot including today) for which to search for
        required: true
        default: 7

env:
  DATA_DIR: "/home/runner/work/medium_scraper/medium_scraper/output"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MEDIUM_BLOG_LOOKBACK_WINDOW: '${{ github.event.inputs.medium_blog_lookback_days }}'

jobs:
  ci_pipeline:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ubuntu-20.04-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - run: pip install -e .

      - run: spacy download en_core_web_sm

      - run: pre-commit run -a

      - run: ingestion

      - run: transformation

      - run: data_products
        env:
          RECIPIENT_EMAIL_ADDRESS: 123@mailslurp.com
          SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
          SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}

  dev_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build container and run commands
        uses: devcontainers/ci@v0.3
        env:
          MEDIUM_BLOG_LOOKBACK_WINDOW: '${{ github.event.inputs.medium_blog_lookback_days }}'
          RECIPIENT_EMAIL_ADDRESS: 123@mailslurp.com
          SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
          SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
        with:
          runCmd: ingestion && transformation && data_products
          env: |
            DATA_DIR=/workspaces/medium_scraper/output
            GITHUB_TOKEN=dummy_value
            MEDIUM_BLOG_LOOKBACK_WINDOW
            RECIPIENT_EMAIL_ADDRESS
            SENDER_EMAIL_ADDRESS
            SENDER_EMAIL_PASSWORD

  automerge_pull_requests:
    needs: [ci_pipeline, dev_container]
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.15.6
        env:
          MERGE_METHOD: "squash"
