name: weekly_run

on:
  schedule:
    - cron: "0 6 * * 5"
  workflow_dispatch:
    inputs:
      ingestion_lookback_days:
        description: The number of days into the past for which to ingest data for
        required: true
        default: 7

env:
  DATA_DIR: "/home/runner/work/medium_scraper/medium_scraper/output"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INGESTION_LOOKBACK_WINDOW: '${{ github.event.inputs.ingestion_lookback_days || 7}}'
  PAT_GITHUB:  ${{ secrets.PAT_GITHUB }}

jobs:
  weekly_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ubuntu-20.04-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - run: pip install -e .

      - run: spacy download en_core_web_sm

      - run: ingestion

      - run: transformation

      - run: data_products
        env:
          SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
          SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
          RECIPIENT_EMAIL_ADDRESS: ${{ secrets.RECIPIENT_EMAIL_ADDRESS }}

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Github Actions
          author_email: actions@github.com
          new_branch: weekly_run_branch_${{ github.run_id }}

      # To ensure the PR triggers CI workflows it needs to use someone's PAT instead of the default GITHUB_TOKEN
      - name: Create Pull Request
        run: |
          export GITHUB_TOKEN= && \
          echo ${{ secrets.PAT_GITHUB }} > token.txt && \
          gh auth login --with-token < token.txt && \
          gh pr create -B main -H weekly_run_branch_${{ github.run_id }} --title 'weekly_run ${{ github.run_id }}' --body 'Created by Github action' --label 'automerge'
