name: weekly_run

on:
  schedule:
    - cron: "0 9 * * 5"
  workflow_dispatch:
    inputs:
      medium_blog_lookback_days:
        description: The number of days (up to but mot including today) for which to search for
        required: true
        default: 7

env:
  DATA_DIR: "/home/runner/work/medium_scraper/medium_scraper/output"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MEDIUM_BLOG_LOOKBACK_WINDOW: '${{ github.event.inputs.medium_blog_lookback_days }}'

jobs:
  weekly_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ubuntu-20.04-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - run: pip install -e .

      - run: ingestion

      - run: transformation

      - run: data_products
        env:
          SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
          SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
          RECIPIENT_EMAIL_ADDRESS: ${{ secrets.RECIPIENT_EMAIL_ADDRESS }}

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Github Actions
          author_email: actions@github.com
          new_branch: weekly_run_branch_${{ github.run_id }}

      - name: GitHub CLI login
        run: |
          sudo apt update && \
          sudo apt install -y gh && \
          export GITHUB_TOKEN= && \
          echo ${{ secrets.PAT_GITHUB }} > token.txt && \
          gh auth login --with-token < token.txt

      - name: Create Pull Request
        run: gh pr create -B main -H weekly_run_branch_${{ github.run_id }} --title 'weekly_run ${{ github.run_id }}' --body 'Created by Github action' --label 'automerge'
